<?php

namespace frontend\controllers;

use common\models\Element;
use common\models\Review;
use common\models\Section;
use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public function beforeAction($action)
    {
        \Yii::$app->request->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionWriteUs()
    {
        $this->enableCsrfValidation = false;
        $data = \Yii::$app->request->post();
        \Yii::$app->mailer
            ->compose('write-us', [
                'data' => $data,
            ])
            ->setFrom(\Yii::$app->params['adminEmail'])
            ->setTo([\Yii::$app->params['companyEmail'], \Yii::$app->params['marketEmail']])
            ->setSubject('Вопрос')
            ->send();
        return $this->redirect(['/site/index']);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => \yii\web\ErrorAction::class,
            ],
            'captcha' => [
                'class' => \yii\captcha\CaptchaAction::class,
//                'fixedVerifyCode' => null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = "main";

        return $this->render('index', [
            'products' => Section::find()->where(['parent_id' => null])->orderBy(['sort' => SORT_ASC])->all(),
            'reviews' => Review::find()->all(),
        ]);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
//        \Yii::error( \Yii::$app->request->isPost );
        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return \yii\widgets\ActiveForm::validate($model);
            }

            if ($model->validate()) {
                \Yii::error('Model valid');
                if ($model->sendEmail()) {
                    \Yii::error('Email is sent');
                    \Yii::$app->session->setFlash('success', \Yii::t('app', 'Your message sent successfully'));
                    return $this->redirect(["/site/index"]);
                } else {
                    \Yii::error('Email is not sent');
                    \Yii::error($model->attributes);
                    Yii::$app->session->setFlash('error', \Yii::t('app', 'There was an error sending your message.'));
                }
            } else {
                \Yii::error('Model not validate');
            }
            return $this->refresh();
        } else {
            \Yii::error($model->errors);
        }

        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionCertificate()
    {
        return $this->render('certificate');
    }
}
