<?php

namespace common\models;

/**
 * @property integer $id
 * @property integer $number
 * @property integer $parent_id
 * @property integer $type
 * @property string $text
 */
class ListItem extends \yii\db\ActiveRecord
{
    const TYPE_DESCRIPTION_LEFT = 0;
    const TYPE_DESCRIPTION_RIGHT = 1;
    const TYPE_TASK = 2;

    public function rules()
    {
        return [
            [['number', 'parent_id', 'type'], 'number'],
            [['text'], 'string'],
        ]; // TODO: Change the autogenerated stub
    }
}
