<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin Panel' => 'Панель Управления',
    'Create Event' => 'Создать Акцию',
    'Create Post' => 'Создать Новость',
    'Created At' => 'Дата Создания',
    'Delete Post' => 'Удалить Новость',
    'Disabled' => 'Выключено',
    'Enabled' => 'Включено',
    'Events' => 'События',
    'Home' => 'Главная',
    'Image' => 'Изображение',
    'Post is successfully saved' => 'Новость успешно сохранена',
    'Posts' => 'Новости',
    'Save' => 'Сохранить',
    'Sliders' => 'Слайдеры',
    'Text' => 'Текст',
    'Title' => 'Название',
    'Update Event' => 'Обновить Акцию',
    'Update Post' => 'Обновить Новость',
    'Update Slider' => 'Обновить Слайдер',
    'View Event' => 'Просмотр Акции',
    'View Post' => 'Просмотр Новости',
    'Branches' => 'Филиалы',
    'Import Feed' => 'Импорт фида'
];
