<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Slide' => 'Добавить слайд',
    'Address' => 'Адрес',
    'Admin Panel' => 'Панель Управления',
    'Branch' => 'Филиал',
    'Branches' => 'Филиалы',
    'Certificates' => 'Сертификаты',
    'City' => 'Город',
    'Configuration' => 'Настройки',
    'Create Branch' => 'Добавить Филиал',
    'Create Certificate' => 'Добавить сертификат',
    'Create Event' => 'Создать Акцию',
    'Create Post' => 'Создать Новость',
    'Create Slider' => 'Создать слайдер',
    'Created At' => 'Дата Создания',
    'Date' => 'Дата',
    'Description' => 'Описание',
    'Delete Post' => 'Удалить Новость',
    'Delete' => 'Удалить',
    'Disabled' => 'Выключено',
    'Email' => 'Email',
    'Enabled' => 'Включено',
    'Events' => 'Акции',
    'File' => 'Файл',
    'Home' => 'Главная',
    'Href' => 'Ссылка',
    'Image' => 'Изображение',
    'Import Feed' => 'Обновить Feed',
    'Is File' => '',
    'Is Main' => 'Использовать на главной',
    'Login' => 'Войти',
    'Logout ({username})' => 'Выйти ({username})',
    'Name' => 'Название',
    'Password' => 'Пароль',
    'Phone' => 'Телефон',
    'Please fill out the following fields to login' => 'Пожалуйста, заполните следующие поля для входа в систему',
    'Post is successfully saved' => 'Новость успешно сохранена',
    'Posts' => 'Новости',
    'Region' => 'Регион',
    'Remember Me' => 'Запомнить меня',
    'Save' => 'Сохранить',
    'Size' => 'Размер',
    'Sliders' => 'Слайдеры',
    'Start Date' => 'Дата Начала',
    'Status' => 'Статус',
    'Technical support' => 'Техническая поддержка',
    'Text' => 'Текст',
    'Title' => 'Название',
    'Type' => 'Тип',
    'Update' => 'Обновить',
    'Update Event' => 'Обновить Акцию',
    'Update Post' => 'Обновить Новость',
    'Update Slider' => 'Обновить Слайдер',
    'Update: {name}' => 'Обновить: {name}',
    'Upload Images' => 'Загрузить картинки',
    'Username' => 'Имя пользователя',
    'Value' => 'Значение',
    'View Event' => 'Просмотр Акции',
    'View Post' => 'Просмотр Новости',
    'View Slider' => 'Просмотр Слайдера',
];
