<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activity' => 'Вид деятельности',
    'Main Image' => 'Основная картинка',
    'Elements' => 'Техника',
    'Type' => 'Тип',
    'Activities' => 'Виды деятельности',
    'Activity ID' => '',
    'Callback ID' => '',
    'Client Address' => 'Адрес клиента',
    'Client Name' => 'Имя клиента',
    'Decision' => 'Решение',
    'Decisions' => 'Решение',
    'Decision Img' => 'Картинка Решение',
    'Element ID' => '',
    'Factor ID' => '',
    'ID' => '',
    'Position' => '',
    'Problem Img' => 'Картинка Проблемы',
    'Problems' => 'Проблемы',
    'Result Addon' => '',
    'Result Img' => 'Картинка Результат',
    'Result Text' => 'Результат',
    'Task Img' => 'Картинка Задачи',
    'Tasks' => 'Задачи',
    'Title' => 'Название',
    'Text' => 'Текст',
    'Image' => 'Изображение',
    'Save' => 'Сохранить',
    'Result' => 'Результат',
    'Update Callback' => 'Редактировать отзыв',
];
