<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cases and Callbacks' => 'Кейсы и отзывы',
    'All' => 'Все',
    'Case' => 'Кейс',
    'Cases' => 'Кейсы',
    'Callback' => 'Отзыв',
    'Callbacks' => 'Отзывы',
    'Select an Activity' => 'Выберите вид деятельности',
    'Select an Element' => 'Выберите тип техники',

    '{n, plural, =0{are no years} =1{is one years} one{are #year} few{are # years} other{are # years}} of successfully work' => '@@{n, plural, =0{Первый год} =1{Один год} one{# год} few{# года} other{# лет}} успешной работы@@',
];
